read:
  #  proto:
  #    pathToDescriptor: "src/test/resources/person.desc"
  subject: "*"

server:
  port: 1111

nats:
  server:
    url: "nats://localhost:4222" # we should make this property required when starting JetStreamDropApplication
