read:
  mode: "proto"
  #  proto:
  #    pathToDescriptor: "src/test/resources/person.desc"
  subject: "*"

server:
  port: 1111

logging:
  level:
    org.jetstreamDrop.monitoring.NatsMonitoringApiClient: DEBUG
